In [1]:
import mysql.connector
import pandas as pd
import passwords

mydb = mysql.connector.connect(
    host = passwords.host,
    user = passwords.user,
    password = passwords.password,
    database = 'bar_invetory'
)

mycursor = mydb.cursor()

In [4]:
typ = input("Select: ")
equ = input("Is (>, <, =): ")
inp = input("To: ")

mycursor.execute(f'''select * from inventory where {typ} {equ} {inp}
            ''')

mydata = mycursor.fetchall()
df = pd.DataFrame(mydata)
df.columns = ("SKU", "Brand", "Liquor", "Subliquor", "Volume", "Price", "Rating", "OrderDate")
df

Select:  Price
Is (>, <, =):  >
To:  10

,SKU,Brand,Liquor,Subliquor,Volume,Price,Rating,OrderDate
0,3 Amigos Anejo Tequila,3 Amigos,Tequila,Anejo,750,35.99,94.0,2020-11-15
1,ABK6 VS Cognac,ABK6,Cognac,VS,750,26.99,NaN,2020-11-15
2,Angel's Envy,Angel's Envy,Whiskey,Bourbon,750,47.99,98.0,2020-11-15
3,Bacardi Banana Rum,Bacardi,Rum,Flavored Rum,1750,19.99,NaN,2020-11-15
4,Bacardi Gran Reserva 10 Year,Bacardi,Rum,Aged Rum,750,39.99,NaN,2020-11-15
...,...,...,...,...,...,...,...,...
75,Southern Comfort 70,Southern Comfort,Liqueur,Southern Comfort,1750,23.99,NaN,2020-12-04
76,Stone Xocoveza Mocha Stout,Stone,Beer,Stout,72,15.99,97.0,2020-12-02
77,Tequila Rose Strawberry Cream,Tequila Rose,Liqueur,Cream Liqeur,1750,79.99,NaN,2020-10-31
78,Two Stars Bourbon,Two Stars,Whiskey,Bourbon,750,19.99,91.0,2020-12-02
79,Woodford Reserve Rye,Woodford,Whiskey,Rye Whiskey,750,31.99,91.0,2020-11-15